spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://booking:wdfA1ccCGgYRrYYS@cluster0.tllgfzl.mongodb.net/smart_campus?retryWrites=true&w=majority
spring.data.mongodb.database=smart_campus
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true 
server.port=8083